# Generated by Django 4.1.3 on 2023-04-17 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='circuits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuitId', models.IntegerField(null=True)),
                ('circuitRef', models.CharField(max_length=25, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=25, null=True)),
                ('lat', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lng', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('alt', models.IntegerField(null=True)),
                ('url', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='constructor_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructorResultsId', models.IntegerField(null=True)),
                ('raceId', models.IntegerField(null=True)),
                ('constructorId', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='constructor_standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructorStandingsId', models.IntegerField(null=True)),
                ('raceId', models.IntegerField(null=True)),
                ('constructorId', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('positionText', models.IntegerField(null=True)),
                ('wins', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='constructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructorId', models.IntegerField(null=True)),
                ('constructorRef', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('nationality', models.CharField(max_length=25, null=True)),
                ('url', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='driver_standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverStandingsId', models.IntegerField(null=True)),
                ('raceId', models.IntegerField(null=True)),
                ('driverId', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('positionText', models.IntegerField(null=True)),
                ('wins', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverId', models.IntegerField(null=True)),
                ('driverRef', models.CharField(max_length=25, null=True)),
                ('number', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=5, null=True)),
                ('forename', models.CharField(max_length=20, null=True)),
                ('surname', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=25, null=True)),
                ('url', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lap_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceId', models.IntegerField(null=True)),
                ('driverId', models.IntegerField(null=True)),
                ('lap', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('milliseconds', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pit_stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceId', models.IntegerField(null=True)),
                ('driverId', models.IntegerField(null=True)),
                ('stop', models.IntegerField(null=True)),
                ('lap', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('milliseconds', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='qualifying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifyId', models.IntegerField(null=True)),
                ('raceId', models.IntegerField(null=True)),
                ('driverId', models.IntegerField(null=True)),
                ('constructorId', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('q1', models.TimeField(null=True)),
                ('q2', models.TimeField(null=True)),
                ('q3', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceId', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('round', models.IntegerField(null=True)),
                ('circuitId', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('url', models.URLField(max_length=300, null=True)),
                ('fp1_date', models.DateField(null=True)),
                ('fp1_time', models.TimeField(null=True)),
                ('fp2_date', models.DateField(null=True)),
                ('fp2_time', models.TimeField(null=True)),
                ('fp3_date', models.DateField(null=True)),
                ('fp3_time', models.TimeField(null=True)),
                ('quali_date', models.DateField(null=True)),
                ('quali_time', models.TimeField(null=True)),
                ('sprint_date', models.DateField(null=True)),
                ('sprint_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultId', models.IntegerField(null=True)),
                ('raceId', models.IntegerField(null=True)),
                ('driverId', models.IntegerField(null=True)),
                ('constructorId', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('grid', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('positionText', models.IntegerField(null=True)),
                ('positionOrder', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('laps', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('milliseconds', models.IntegerField(null=True)),
                ('fastestLap', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('fastestLapTime', models.TimeField(null=True)),
                ('fastestLapSpeed', models.FloatField(null=True)),
                ('statusId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('url', models.URLField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sprint_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultId', models.IntegerField(null=True)),
                ('raceId', models.IntegerField(null=True)),
                ('driverId', models.IntegerField(null=True)),
                ('constructorId', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('grid', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('positionText', models.IntegerField(null=True)),
                ('positionOrder', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('laps', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
                ('milliseconds', models.IntegerField(null=True)),
                ('fastestLap', models.IntegerField(null=True)),
                ('fastestLapTime', models.TimeField(null=True)),
                ('statusId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusId', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
