# Generated by Django 4.1.3 on 2023-04-17 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuits',
            name='alt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='circuitId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='circuitRef',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='country',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='lat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='lng',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_results',
            name='constructorId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_results',
            name='constructorResultsId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_results',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_results',
            name='raceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_results',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_standings',
            name='constructorId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_standings',
            name='constructorStandingsId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_standings',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_standings',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_standings',
            name='positionText',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_standings',
            name='raceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructor_standings',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='constructorId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='constructorRef',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='nationality',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='driver_standings',
            name='driverId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_standings',
            name='driverStandingsId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_standings',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_standings',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_standings',
            name='positionText',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_standings',
            name='raceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_standings',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='driverId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='driverRef',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='forename',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='nationality',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lap_times',
            name='driverId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap_times',
            name='lap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap_times',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap_times',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap_times',
            name='raceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap_times',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stops',
            name='driverId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stops',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stops',
            name='lap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stops',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stops',
            name='raceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stops',
            name='stop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pit_stops',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='constructorId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='driverId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='q1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='q2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='q3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='qualifyId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='raceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='circuitId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp1_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp2_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp3_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='quali_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='quali_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='raceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='sprint_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='sprint_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='constructorId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='driverId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='fastestLap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='fastestLapSpeed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='fastestLapTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='grid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='positionOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='positionText',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='raceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='resultId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='statusId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='constructorId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='driverId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='fastestLap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='fastestLapTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='grid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='positionOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='positionText',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='raceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='resultId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='statusId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='statusId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
