# Generated by Django 4.1.3 on 2023-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_stats', '0004_alter_constructor_results_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_standings',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_standings',
            name='positionText',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='positionText',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='positionText',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
