# Generated by Django 4.1.3 on 2023-04-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_stats', '0005_alter_driver_standings_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifying',
            name='q1',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='q2',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='q3',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='fastestLapTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='fastestLapTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
