# Generated by Django 4.1.3 on 2023-04-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_stats', '0008_alter_pit_stops_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap_times',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
